openapi: 3.0.0
info:
  contact:
    email: snowman@groups.sap.com
    url: https://github.com/HPI-Information-Systems/snowman
  description: |
    _This document describes the REST API of the snowman data matching benchmark tool._ Comparing data matching algorithms is still an unsolved topic in both industry and research. With snowman, developers and researchers will be able to compare the performance of different data matching solutions or improve new algorithms.
  license:
    name: LICENSE (MIT)
    url: https://github.com/HPI-Information-Systems/snowman/blob/main/LICENSE
  title: Snowman API
  version: 1.0.0
servers:
- url: '{protocol}://{server}/api/v1'
  variables:
    protocol:
      default: http
      enum:
      - http
      - https
    server:
      default: localhost:8123
tags:
- description: Operations about algorithms
  name: Algorithm
- description: Operations about datasets
  name: Datasets
- description: Operations about experiments
  name: Experiments
- description: Operations about similarity thresholds of experiments
  name: Similarity Thresholds
- description: Operations about comparing multiple experiments
  name: Benchmark
paths:
  /algorithms:
    get:
      operationId: getAlgorithms
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Algorithm'
                type: array
          description: OK
      summary: Get all algorithms
      tags:
      - Algorithm
      x-eov-operation-handler: controllers/AlgorithmController
    post:
      operationId: addAlgorithm
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlgorithmValues'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AlgorithmId'
          description: Created
        "400":
          description: Bad Request
      summary: Creates a new algorithm
      tags:
      - Algorithm
      x-codegen-request-body-name: algorithm
      x-eov-operation-handler: controllers/AlgorithmController
  /algorithms/{algorithmId}:
    delete:
      operationId: deleteAlgorithm
      parameters:
      - explode: false
        in: path
        name: algorithmId
        required: true
        schema:
          $ref: '#/components/schemas/AlgorithmId'
        style: simple
      responses:
        "204":
          description: No Content
      summary: Deletes an algorithm by id
      tags:
      - Algorithm
      x-eov-operation-handler: controllers/AlgorithmController
    get:
      operationId: getAlgorithm
      parameters:
      - explode: false
        in: path
        name: algorithmId
        required: true
        schema:
          $ref: '#/components/schemas/AlgorithmId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Algorithm'
          description: OK
        "404":
          description: Not Found
      summary: Gets an algorithm by id
      tags:
      - Algorithm
      x-eov-operation-handler: controllers/AlgorithmController
    put:
      operationId: setAlgorithm
      parameters:
      - explode: false
        in: path
        name: algorithmId
        required: true
        schema:
          $ref: '#/components/schemas/AlgorithmId'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AlgorithmValues'
        required: true
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Updates or creates an algorithm
      tags:
      - Algorithm
      x-codegen-request-body-name: algorithm
      x-eov-operation-handler: controllers/AlgorithmController
  /datasets:
    get:
      operationId: getDatasets
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Dataset'
                type: array
          description: OK
      summary: Returns all Datasets
      tags:
      - Datasets
      x-eov-operation-handler: controllers/DatasetsController
    post:
      operationId: addDataset
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetValues'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DatasetId'
          description: Created
        "400":
          description: Bad Request
      summary: Creates a new dataset with metainformation
      tags:
      - Datasets
      x-codegen-request-body-name: dataset
      x-eov-operation-handler: controllers/DatasetsController
  /datasets/{datasetId}:
    delete:
      operationId: deleteDataset
      parameters:
      - explode: false
        in: path
        name: datasetId
        required: true
        schema:
          $ref: '#/components/schemas/DatasetId'
        style: simple
      responses:
        "204":
          description: No Content
      summary: Deletes a whole dataset by id
      tags:
      - Datasets
      x-eov-operation-handler: controllers/DatasetsController
    get:
      operationId: getDataset
      parameters:
      - explode: false
        in: path
        name: datasetId
        required: true
        schema:
          $ref: '#/components/schemas/DatasetId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Dataset'
          description: OK
        "404":
          description: Not Found
      summary: Gets dataset by id
      tags:
      - Datasets
      x-eov-operation-handler: controllers/DatasetsController
    put:
      operationId: setDataset
      parameters:
      - explode: false
        in: path
        name: datasetId
        required: true
        schema:
          $ref: '#/components/schemas/DatasetId'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DatasetValues'
        required: true
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Updates or creates a dataset
      tags:
      - Datasets
      x-codegen-request-body-name: dataset
      x-eov-operation-handler: controllers/DatasetsController
  /datasets/{datasetId}/file:
    delete:
      operationId: deleteDatasetFile
      parameters:
      - explode: false
        in: path
        name: datasetId
        required: true
        schema:
          $ref: '#/components/schemas/DatasetId'
        style: simple
      responses:
        "204":
          description: No Content
      summary: Deletes a dataset file (but not the dataset)
      tags:
      - Datasets
      x-eov-operation-handler: controllers/DatasetsController
    get:
      description: Always returns one row with column names followed by the requested
        amount of rows. To only return the column names, pass startAt=0 and limit=0.
      operationId: getDatasetFile
      parameters:
      - explode: false
        in: path
        name: datasetId
        required: true
        schema:
          $ref: '#/components/schemas/DatasetId'
        style: simple
      - explode: true
        in: query
        name: startAt
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - description: -1 returns all remaining records
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: -1
          type: integer
        style: form
      - description: startAt and limit can be used without specifying sortBy (guarantees
          same order of records even if not specified)
        explode: true
        in: query
        name: sortBy
        required: false
        schema:
          example: first_name
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: OK
        "404":
          description: Not Found
      summary: Gets a dataset file by id
      tags:
      - Datasets
      x-eov-operation-handler: controllers/DatasetsController
    put:
      operationId: setDatasetFile
      parameters:
      - explode: false
        in: path
        name: datasetId
        required: true
        schema:
          $ref: '#/components/schemas/DatasetId'
        style: simple
      - description: The name of the alphanumeric id column in the uploaded dataset.
        explode: true
        in: query
        name: idColumn
        required: true
        schema:
          example: id
          type: string
        style: form
      - explode: true
        in: query
        name: quote
        required: true
        schema:
          example: '"'
          type: string
        style: form
      - explode: true
        in: query
        name: escape
        required: true
        schema:
          example: ''''
          type: string
        style: form
      - explode: true
        in: query
        name: separator
        required: true
        schema:
          example: ','
          type: string
        style: form
      requestBody:
        content:
          text/csv:
            schema:
              $ref: '#/components/schemas/CSVFile'
        required: true
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Updates or creates a dataset file
      tags:
      - Datasets
      x-codegen-request-body-name: file
      x-eov-operation-handler: controllers/DatasetsController
  /experiments:
    get:
      operationId: getExperiments
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Experiment'
                type: array
          description: OK
      summary: Get all experiments
      tags:
      - Experiments
      x-eov-operation-handler: controllers/ExperimentsController
    post:
      operationId: addExperiment
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExperimentValues'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExperimentId'
          description: Created
        "400":
          description: Bad Request
      summary: Creates a new Experiment
      tags:
      - Experiments
      x-codegen-request-body-name: experiment
      x-eov-operation-handler: controllers/ExperimentsController
  /experiments/{experimentId}:
    delete:
      operationId: deleteExperiment
      parameters:
      - explode: false
        in: path
        name: experimentId
        required: true
        schema:
          $ref: '#/components/schemas/ExperimentId'
        style: simple
      responses:
        "204":
          description: No Content
      summary: Deletes an experiment (including experiment file)
      tags:
      - Experiments
      x-eov-operation-handler: controllers/ExperimentsController
    get:
      operationId: getExperiment
      parameters:
      - explode: false
        in: path
        name: experimentId
        required: true
        schema:
          $ref: '#/components/schemas/ExperimentId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Experiment'
          description: OK
        "404":
          description: Not Found
      summary: Gets experiment by id
      tags:
      - Experiments
      x-eov-operation-handler: controllers/ExperimentsController
    put:
      operationId: setExperiment
      parameters:
      - explode: false
        in: path
        name: experimentId
        required: true
        schema:
          $ref: '#/components/schemas/ExperimentId'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ExperimentValues'
        required: true
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Updates or creates an Experiment
      tags:
      - Experiments
      x-codegen-request-body-name: experiment
      x-eov-operation-handler: controllers/ExperimentsController
  /experiments/{experimentId}/file:
    get:
      operationId: getExperimentFile
      parameters:
      - explode: false
        in: path
        name: experimentId
        required: true
        schema:
          $ref: '#/components/schemas/ExperimentId'
        style: simple
      - description: only use in combination with similarityThreshold
        explode: true
        in: query
        name: similarityThresholdFunction
        required: false
        schema:
          $ref: '#/components/schemas/SimilarityThresholdFunctionId'
        style: form
      - description: only use in combination with similarityThresholdFunction
        explode: true
        in: query
        name: similarityThreshold
        required: false
        schema:
          type: number
        style: form
      - explode: true
        in: query
        name: startAt
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - description: -1 returns all remaining records
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: -1
          type: integer
        style: form
      - description: startAt and limit can be used without specifying sortBy (guarantees
          same order of records even if not specified)
        explode: true
        in: query
        name: sortBy
        required: false
        schema:
          example: first_name
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: OK
        "404":
          description: Not Found
      summary: Get an experiment file
      tags:
      - Experiments
      x-eov-operation-handler: controllers/ExperimentsController
    put:
      operationId: setExperimentFile
      parameters:
      - explode: false
        in: path
        name: experimentId
        required: true
        schema:
          $ref: '#/components/schemas/ExperimentId'
        style: simple
      - description: only use in combination with similarityThreshold
        explode: true
        in: query
        name: similarityThresholdFunction
        required: false
        schema:
          $ref: '#/components/schemas/SimilarityThresholdFunctionId'
        style: form
      - description: only use in combination with similarityThresholdFunction
        explode: true
        in: query
        name: similarityThreshold
        required: false
        schema:
          type: number
        style: form
      - description: 'Documentation on the formats can be found here: https://hpi-information-systems.github.io/snowman/basic_usage/experiments/#import-formats'
        explode: true
        in: query
        name: format
        required: true
        schema:
          enum:
          - magellan
          - clusterER
          - pilot
          - sigmod2021
          - BHANA
          - BPIES
          type: string
        style: form
      requestBody:
        content:
          text/csv:
            schema:
              $ref: '#/components/schemas/CSVFile'
        required: true
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Creates an experiment file (cannot overwrite existing)
      tags:
      - Experiments
      x-codegen-request-body-name: file
      x-eov-operation-handler: controllers/ExperimentsController
  /similarity-threshold-functions:
    get:
      operationId: getSimilarityThresholdFunctions
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/SimilarityThresholdFunction'
                type: array
          description: OK
        "404":
          description: Not Found
      summary: Get all similarity threshold functions
      tags:
      - Similarity Thresholds
      x-eov-operation-handler: controllers/SimilarityThresholdsController
    post:
      operationId: addSimilarityThresholdFunction
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimilarityThresholdFunctionValues'
        required: true
      responses:
        "201":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimilarityThresholdFunctionId'
          description: Created
        "400":
          description: Bad Request
      summary: Creates a new similarity threshold function
      tags:
      - Similarity Thresholds
      x-codegen-request-body-name: similarityThresholdFunction
      x-eov-operation-handler: controllers/SimilarityThresholdsController
  /similarity-threshold-functions/{functionId}:
    delete:
      operationId: deleteSimilarityThresholdFunction
      parameters:
      - explode: false
        in: path
        name: functionId
        required: true
        schema:
          $ref: '#/components/schemas/SimilarityThresholdFunctionId'
        style: simple
      responses:
        "204":
          description: No Content
      summary: Deletes a similarity threshold function
      tags:
      - Similarity Thresholds
      x-eov-operation-handler: controllers/SimilarityThresholdsController
    get:
      operationId: getSimilarityThresholdFunction
      parameters:
      - explode: false
        in: path
        name: functionId
        required: true
        schema:
          $ref: '#/components/schemas/SimilarityThresholdFunctionId'
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SimilarityThresholdFunction'
          description: OK
        "404":
          description: Not Found
      summary: Get a similarity threshold function
      tags:
      - Similarity Thresholds
      x-eov-operation-handler: controllers/SimilarityThresholdsController
    put:
      operationId: setSimilarityThresholdFunction
      parameters:
      - explode: false
        in: path
        name: functionId
        required: true
        schema:
          $ref: '#/components/schemas/SimilarityThresholdFunctionId'
        style: simple
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SimilarityThresholdFunctionValues'
        required: true
      responses:
        "204":
          description: No Content
        "400":
          description: Bad Request
      summary: Updates or creates a similarity threshold function
      tags:
      - Similarity Thresholds
      x-codegen-request-body-name: similarityThresholdFunction
      x-eov-operation-handler: controllers/SimilarityThresholdsController
  /benchmark/metrics:
    get:
      operationId: getBinaryMetrics
      parameters:
      - explode: true
        in: query
        name: groundTruthExperimentId
        required: true
        schema:
          $ref: '#/components/schemas/ExperimentId'
        style: form
      - description: only use in combination with groundTruthSimilarityThreshold
        explode: true
        in: query
        name: groundTruthSimilarityThresholdFunction
        required: false
        schema:
          $ref: '#/components/schemas/SimilarityThresholdFunctionId'
        style: form
      - description: only use in combination with groundTruthSimilarityThresholdFunction
        explode: true
        in: query
        name: groundTruthSimilarityThreshold
        required: false
        schema:
          type: number
        style: form
      - explode: true
        in: query
        name: predictedExperimentId
        required: true
        schema:
          $ref: '#/components/schemas/ExperimentId'
        style: form
      - description: only use in combination with predictedSimilarityThreshold
        explode: true
        in: query
        name: predictedSimilarityThresholdFunction
        required: false
        schema:
          $ref: '#/components/schemas/SimilarityThresholdFunctionId'
        style: form
      - description: only use in combination with predictedSimilarityThresholdFunction
        explode: true
        in: query
        name: predictedSimilarityThreshold
        required: false
        schema:
          type: number
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/Metric'
                type: array
          description: OK
        "404":
          description: Not Found
      summary: Compares two experiments and returns binary metrics
      tags:
      - Benchmark
      x-eov-operation-handler: controllers/BenchmarkController
  /benchmark/experiment-intersection/records:
    post:
      operationId: calculateExperimentIntersectionRecords
      parameters:
      - explode: true
        in: query
        name: startAt
        required: false
        schema:
          default: 0
          type: integer
        style: form
      - description: -1 returns all remaining records
        explode: true
        in: query
        name: limit
        required: false
        schema:
          default: -1
          type: integer
        style: form
      requestBody:
        $ref: '#/components/requestBodies/ExperimentIntersection'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/FileResponse'
          description: OK
        "404":
          description: Not Found
      summary: intersects multiple experiments and returns the resulting records.
        This can be used to calculate the confusion-matrix.
      tags:
      - Benchmark
      x-codegen-request-body-name: intersection
      x-eov-operation-handler: controllers/BenchmarkController
  /benchmark/experiment-intersection/count:
    post:
      operationId: calculateExperimentIntersectionCount
      requestBody:
        $ref: '#/components/requestBodies/ExperimentIntersection'
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ExperimentIntersectionCount'
          description: OK
        "404":
          description: Not Found
      summary: Intersects multiple experiments and returns the count of pairs and
        the count of rows. This can be used to calculate the confusion-matrix.
      tags:
      - Benchmark
      x-codegen-request-body-name: intersection
      x-eov-operation-handler: controllers/BenchmarkController
  /benchmark/experiment-intersection/counts:
    post:
      description: Returns the pair and row counts of all possible intersections of
        the given experiments.
      operationId: calculateExperimentIntersectionCounts
      requestBody:
        content:
          application/json:
            schema:
              items:
                $ref: '#/components/schemas/ExperimentConfigItem'
              type: array
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                items:
                  $ref: '#/components/schemas/ExperimentIntersectionCount'
                type: array
          description: OK
        "404":
          description: Not Found
      tags:
      - Benchmark
      x-codegen-request-body-name: experiments
      x-eov-operation-handler: controllers/BenchmarkController
  /benchmark/diagram:
    post:
      description: returns diagram data based on two metrics and multiple experiments
      operationId: calculateDiagramData
      parameters:
      - description: metric to be visualised on the x-axis of the diagram
        explode: true
        in: query
        name: xAxis
        required: true
        schema:
          anyOf:
          - $ref: '#/components/schemas/softKPIsAlgorithmEnum'
          - $ref: '#/components/schemas/MetricsEnum'
          - $ref: '#/components/schemas/softKPIsExperimentEnum'
        style: form
      - description: metric to be visualised on the y-axis of the diagram
        explode: true
        in: query
        name: yAxis
        required: true
        schema:
          anyOf:
          - $ref: '#/components/schemas/softKPIsAlgorithmEnum'
          - $ref: '#/components/schemas/MetricsEnum'
          - $ref: '#/components/schemas/softKPIsExperimentEnum'
        style: form
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                multipleExperiments:
                  items:
                    $ref: '#/components/schemas/DiagramExperimentItem'
                  type: array
                similarityThresholds:
                  $ref: '#/components/schemas/ExperimentSimilarityConfig'
              type: object
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/DiagramResponse'
          description: OK
        "403":
          description: Forbidden
        "404":
          description: Experiments or metrics not found
      tags:
      - Benchmark
      x-codegen-request-body-name: diagram
      x-eov-operation-handler: controllers/BenchmarkController
components:
  requestBodies:
    ExperimentIntersection:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ExperimentIntersection'
      required: true
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
  schemas:
    AlgorithmId:
      example: 1
      type: integer
    AlgorithmValues:
      example:
        softKPIs:
          integrationEffort:
            installationEffort:
              expertise: 0
              hrAmount: 6
            deploymentType:
            - cloud
            - cloud
            useCase:
            - merging
            - merging
            generalCosts: 1
            solutionType:
            - rulebased
            - rulebased
          configurationEffort:
            interfaces:
            - GUI
            - GUI
            matchingSolution:
              expertise: 0
              hrAmount: 6
            domain:
              expertise: 0
              hrAmount: 6
            supportedOSs:
            - Windows
            - Windows
        name: Magellan
        description: This is an open source python library
      properties:
        name:
          example: Magellan
          minLength: 1
          type: string
        description:
          example: This is an open source python library
          type: string
        softKPIs:
          $ref: '#/components/schemas/AlgorithmValues_softKPIs'
      required:
      - name
      type: object
    Algorithm:
      allOf:
      - $ref: '#/components/schemas/Algorithm_allOf'
      - $ref: '#/components/schemas/AlgorithmValues'
    DatasetId:
      example: 1
      type: integer
    DatasetValues:
      example:
        numberOfRecords: 500
        name: Dataset1
        description: This is a dataset file about Restaurants.
        tags:
        - restaurants
        - restaurants
      properties:
        name:
          example: Dataset1
          minLength: 1
          type: string
        description:
          example: This is a dataset file about Restaurants.
          type: string
        numberOfRecords:
          example: 500
          type: integer
        tags:
          items:
            example: restaurants
            type: string
          type: array
      required:
      - name
      type: object
    Dataset:
      allOf:
      - $ref: '#/components/schemas/Dataset_allOf'
      - $ref: '#/components/schemas/DatasetValues'
    ExperimentId:
      example: 1
      type: integer
    ExperimentValues:
      example:
        softKPIs:
          runtime: 0
          effort:
            expertise: 0
            hrAmount: 6
        name: Experiment1
        description: This is an experiment using a fancy algorithm
        datasetId: 1
        algorithmId: 1
      properties:
        name:
          example: Experiment1
          minLength: 1
          type: string
        description:
          example: This is an experiment using a fancy algorithm
          type: string
        datasetId:
          example: 1
          type: integer
        algorithmId:
          example: 1
          type: integer
        softKPIs:
          $ref: '#/components/schemas/ExperimentValues_softKPIs'
      required:
      - algorithmId
      - datasetId
      - name
      type: object
    Experiment:
      allOf:
      - $ref: '#/components/schemas/Experiment_allOf'
      - $ref: '#/components/schemas/ExperimentValues'
    SimilarityThresholdFunctionId:
      type: integer
    SimilarityThreshold:
      type: string
    SimilarityThresholdFunctionConstant:
      type: number
    SimilarityThresholdFunctionOperator:
      properties:
        left:
          $ref: '#/components/schemas/SimilarityThresholdFunctionDefinition'
        right:
          $ref: '#/components/schemas/SimilarityThresholdFunctionDefinition'
        operator:
          enum:
          - ADD
          - SUBTRACT
          - MULTIPLY
          - DIVIDE
          - POWER
          - POW
          - ATAN2
          - LOG
          - MOD
          type: string
      required:
      - left
      - operator
      - right
      type: object
    SimilarityThresholdFunctionUnaryOperator:
      properties:
        func:
          $ref: '#/components/schemas/SimilarityThresholdFunctionDefinition'
        operator:
          enum:
          - ACOS
          - ACOSH
          - ASIN
          - ASINH
          - ATAN
          - ATANH
          - CEIL
          - CEILING
          - COS
          - COSH
          - DEGREES
          - EXP
          - FLOOR
          - LN
          - LOG
          - LOG10
          - LOG2
          - RADIANS
          - SIN
          - SINH
          - SQRT
          - TAN
          - TANH
          - TRUNC
          type: string
      required:
      - func
      - operator
      type: object
    SimilarityThresholdFunctionDefinition:
      properties:
        type:
          enum:
          - SimilarityThreshold
          - Operator
          - Constant
          - UnaryOperator
          type: string
        similarityThreshold:
          type: string
        operator:
          $ref: '#/components/schemas/SimilarityThresholdFunctionOperator'
        constant:
          type: number
        unaryOperator:
          $ref: '#/components/schemas/SimilarityThresholdFunctionUnaryOperator'
      required:
      - type
      type: object
    SimilarityThresholdFunctionValues:
      allOf:
      - $ref: '#/components/schemas/SimilarityThresholdFunctionValues_allOf'
    SimilarityThresholdFunction:
      allOf:
      - $ref: '#/components/schemas/SimilarityThresholdFunction_allOf'
      - $ref: '#/components/schemas/SimilarityThresholdFunctionValues'
    Metric:
      example:
        name: precision
        formula: \frac{truePositives}{truePositives + falsePositives}
        range:
        - 0
        - 1
        id: id
        value: 0.75
        info: The meaningfulness of the f1 score is debated in the research community.
        infoLink: https://link.springer.com/article/10.1007/s11222-017-9746-6
      properties:
        name:
          example: precision
          type: string
        id:
          type: string
        formula:
          example: \frac{truePositives}{truePositives + falsePositives}
          type: string
        info:
          example: The meaningfulness of the f1 score is debated in the research community.
          type: string
        infoLink:
          example: https://link.springer.com/article/10.1007/s11222-017-9746-6
          type: string
        value:
          example: 0.75
          type: number
        range:
          example:
          - 0
          - 1
          items:
            type: number
          maxItems: 2
          minItems: 2
          type: array
      required:
      - formula
      - name
      - value
      type: object
    ExperimentConfigItem:
      example:
        similarity:
          func: 0
          threshold: 6.027456183070403
        experimentId: 1
      properties:
        experimentId:
          example: 1
          type: integer
        similarity:
          $ref: '#/components/schemas/ExperimentConfigItem_similarity'
      required:
      - experimentId
      type: object
    ExperimentIntersectionItem:
      allOf:
      - $ref: '#/components/schemas/ExperimentConfigItem'
      - $ref: '#/components/schemas/ExperimentIntersectionItem_allOf'
    ExperimentIntersection:
      items:
        $ref: '#/components/schemas/ExperimentIntersectionItem'
      type: array
    ExperimentIntersectionCount:
      example:
        experiments:
        - null
        - null
        numberRows: 5
        numberPairs: 10
      properties:
        numberRows:
          example: 5
          type: integer
        numberPairs:
          example: 10
          type: integer
        experiments:
          items:
            $ref: '#/components/schemas/ExperimentIntersectionItem'
          type: array
      required:
      - experiments
      - numberPairs
      - numberRows
      type: object
    EffortParts:
      example:
        expertise: 0
        hrAmount: 6
      properties:
        expertise:
          type: integer
        hrAmount:
          type: integer
      type: object
    ExperimentSimilarityConfig:
      properties:
        experimentId:
          example: 1
          type: integer
        groundTruthId:
          example: 1
          type: integer
        steps:
          type: integer
        func:
          type: integer
      required:
      - experimentId
      - func
      - groundTruthId
      - steps
    DiagramExperimentItem:
      properties:
        experiment:
          $ref: '#/components/schemas/ExperimentConfigItem'
        groundTruth:
          $ref: '#/components/schemas/ExperimentConfigItem'
      required:
      - experiment
      type: object
    DiagramExperiments:
      items:
        $ref: '#/components/schemas/DiagramExperimentItem'
      type: array
    DiagramCoordinates:
      example:
        x: 0.8008281904610115
        y: 6.027456183070403
        experimentId: 1
        threshold: 5.962133916683182
        funcId: 1
      properties:
        x:
          type: number
        y:
          type: number
        funcId:
          type: integer
        experimentId:
          example: 1
          type: integer
        threshold:
          type: number
      required:
      - x
      - "y"
    softKPIsAlgorithmEnum:
      enum:
      - domainExpertise
      - domainHrAmount
      - domainManhattanDistanceBasedEffort
      - domainHrAmountWeightedEffort
      - domainMultiplyEffort
      - domainExpertiseWeightedEffort
      - matchingSolutionExpertise
      - matchingSolutionHrAmount
      - matchingSolutionManhattanDistanceBasedEffort
      - matchingSolutionHrAmountWeightedEffort
      - matchingSolutionMultiplyEffort
      - matchingSolutionExpertiseWeightedEffort
      - generalCosts
      - installationExpertise
      - installationHrAmount
      - installationManhattanDistanceBasedEffort
      - installationHrAmountWeightedEffort
      - installationMultiplyEffort
      - installationExpertiseWeightedEffort
      type: string
    softKPIsExperimentEnum:
      enum:
      - expertise
      - hrAmount
      - manhattanDistanceBasedEffort
      - hrAmountWeightedEffort
      - multiplyEffort
      - expertiseWeightedEffort
      - runtime
      type: string
    MetricsEnum:
      enum:
      - similarity
      - falseDiscoveryRate
      - falseNegativeRate
      - falseOmissionRate
      - falsePositiveRate
      - negativePredictiveValue
      - precision
      - prevalenceThreshold
      - recall
      - specificity
      - threatScore
      - accuracy
      - balancedAccuracy
      - bookmakerInformedness
      - fStarScore
      - f1Score
      - fowlkesMallowsIndex
      - markedness
      - matthewsCorrelationCoefficient
      type: string
    DiagramResponse:
      example:
        valueRange:
        - 0
        - 1
        coordinates:
        - x: 0.8008281904610115
          y: 6.027456183070403
          experimentId: 1
          threshold: 5.962133916683182
          funcId: 1
        - x: 0.8008281904610115
          y: 6.027456183070403
          experimentId: 1
          threshold: 5.962133916683182
          funcId: 1
        definitionRange:
        - 0
        - 1
      properties:
        coordinates:
          items:
            $ref: '#/components/schemas/DiagramCoordinates'
          type: array
        definitionRange:
          example:
          - 0
          - 1
          items:
            type: number
          maxItems: 2
          minItems: 2
          type: array
        valueRange:
          example:
          - 0
          - 1
          items:
            type: number
          maxItems: 2
          minItems: 2
          type: array
      required:
      - coordinates
    CSVFile:
      format: binary
      type: string
    FileResponse:
      example:
        data:
        - - "1"
          - test value 1
          - test value 2
        - - "2"
          - test value 1
          - test value 2
        - []
        - - "3"
          - other
          - group
        header:
        - id
        - testColumn1
        - testColumn2
      properties:
        header:
          example:
          - id
          - testColumn1
          - testColumn2
          items:
            type: string
          type: array
        data:
          example:
          - - "1"
            - test value 1
            - test value 2
          - - "2"
            - test value 1
            - test value 2
          - []
          - - "3"
            - other
            - group
          items:
            example:
            - "1"
            - test value 1
            - test value 2
            items:
              type: string
            type: array
          type: array
      required:
      - data
      - header
      type: object
    inline_object:
      properties:
        multipleExperiments:
          items:
            $ref: '#/components/schemas/DiagramExperimentItem'
          type: array
        similarityThresholds:
          $ref: '#/components/schemas/ExperimentSimilarityConfig'
      type: object
    AlgorithmValues_softKPIs_integrationEffort:
      example:
        installationEffort:
          expertise: 0
          hrAmount: 6
        deploymentType:
        - cloud
        - cloud
        useCase:
        - merging
        - merging
        generalCosts: 1
        solutionType:
        - rulebased
        - rulebased
      properties:
        installationEffort:
          $ref: '#/components/schemas/EffortParts'
        deploymentType:
          items:
            example: cloud
            type: string
          type: array
        solutionType:
          items:
            example: rulebased
            type: string
          type: array
        useCase:
          items:
            example: merging
            type: string
          type: array
        generalCosts:
          type: integer
      type: object
    AlgorithmValues_softKPIs_configurationEffort:
      example:
        interfaces:
        - GUI
        - GUI
        matchingSolution:
          expertise: 0
          hrAmount: 6
        domain:
          expertise: 0
          hrAmount: 6
        supportedOSs:
        - Windows
        - Windows
      properties:
        matchingSolution:
          $ref: '#/components/schemas/EffortParts'
        domain:
          $ref: '#/components/schemas/EffortParts'
        interfaces:
          items:
            example: GUI
            type: string
          type: array
        supportedOSs:
          items:
            example: Windows
            type: string
          type: array
      type: object
    AlgorithmValues_softKPIs:
      example:
        integrationEffort:
          installationEffort:
            expertise: 0
            hrAmount: 6
          deploymentType:
          - cloud
          - cloud
          useCase:
          - merging
          - merging
          generalCosts: 1
          solutionType:
          - rulebased
          - rulebased
        configurationEffort:
          interfaces:
          - GUI
          - GUI
          matchingSolution:
            expertise: 0
            hrAmount: 6
          domain:
            expertise: 0
            hrAmount: 6
          supportedOSs:
          - Windows
          - Windows
      properties:
        integrationEffort:
          $ref: '#/components/schemas/AlgorithmValues_softKPIs_integrationEffort'
        configurationEffort:
          $ref: '#/components/schemas/AlgorithmValues_softKPIs_configurationEffort'
      type: object
    Algorithm_allOf:
      properties:
        id:
          example: 1
          type: integer
        matchingSolutionEffort:
          items:
            $ref: '#/components/schemas/Metric'
          type: array
        domainEffort:
          items:
            $ref: '#/components/schemas/Metric'
          type: array
        installationEffort:
          items:
            $ref: '#/components/schemas/Metric'
          type: array
      required:
      - id
      type: object
    Dataset_allOf:
      properties:
        id:
          example: 1
          type: integer
        numberOfUploadedRecords:
          example: 2005
          type: integer
      required:
      - id
      type: object
    ExperimentValues_softKPIs:
      example:
        runtime: 0
        effort:
          expertise: 0
          hrAmount: 6
      properties:
        effort:
          $ref: '#/components/schemas/EffortParts'
        runtime:
          type: integer
      type: object
    Experiment_allOf:
      properties:
        id:
          example: 1
          type: integer
        numberOfUploadedRecords:
          example: 2005
          type: integer
        effort:
          items:
            $ref: '#/components/schemas/Metric'
          type: array
      required:
      - id
      type: object
    SimilarityThresholdFunctionValues_allOf:
      properties:
        name:
          type: string
        experimentId:
          example: 1
          type: integer
        definition:
          $ref: '#/components/schemas/SimilarityThresholdFunctionDefinition'
      required:
      - definition
      - experimentId
      - name
    SimilarityThresholdFunction_allOf:
      properties:
        id:
          type: integer
      required:
      - id
      type: object
    ExperimentConfigItem_similarity:
      example:
        func: 0
        threshold: 6.027456183070403
      properties:
        func:
          type: integer
        threshold:
          type: number
      required:
      - func
      - threshold
      type: object
    ExperimentIntersectionItem_allOf:
      properties:
        predictedCondition:
          type: boolean
      required:
      - predictedCondition
      type: object
